"""
rebuild_company_intel.py
========================
Rewrites CompanyIntel.js (the 12-tab intelligence placemat) to source all
company data from capiq_export.json instead of broken FMP API calls.

Writes the new component to:
  E:\\PowerAcademy\\app\\poweracademy\\src\\components\\CompanyIntel.js

NEVER uses PowerShell string manipulation. Always writes via Python
open(path, 'w', encoding='utf-8') to avoid Unicode corruption.

Run from any directory:
  python rebuild_company_intel.py

Tabs rebuilt:
  0  Overview       — description, S&P rating, executives
  1  Financials     — revenue, EBITDA, net income, EPS, CFO, capex
  2  Rate Base      — mgmt-disclosed (EDGAR), rate case filings, balance sheet fallback
  3  Customers      — total customers, breakdown if available
  4  CapEx Plan     — planned_capex from capiq; rate base growth bridge
  5  Dividends      — div yield, payout, history
  6  Valuation      — market cap, TEV, P/E, EV/EBITDA multiples
  7  Guidance       — guidance dict from capiq
  8  Rate Cases     — pending + past rate cases with amounts & decisions
  9  Transactions   — M&A / asset sales from capiq transactions field
  10 Top Holders    — institutional holders table
  11 Map            — embedded mini-map (existing MapTab component)
"""

import json
import os
import sys
from pathlib import Path

# ── Paths ─────────────────────────────────────────────────────────────────────
SCRIPT_DIR   = Path(__file__).parent
DATA_DIR     = SCRIPT_DIR.parent / "data"
CAPIQ_PATH   = DATA_DIR / "capiq_export.json"

APP_SRC      = Path(r"E:\PowerAcademy\app\poweracademy\src")
COMPONENTS   = APP_SRC / "components"
OUT_PATH     = COMPONENTS / "CompanyIntel.js"

# ── Verify paths ──────────────────────────────────────────────────────────────
if not CAPIQ_PATH.exists():
    sys.exit(f"ERROR: capiq_export.json not found at {CAPIQ_PATH}")

with open(CAPIQ_PATH, "r", encoding="utf-8") as f:
    CAPIQ = json.load(f)

print(f"Loaded capiq_export.json — {len(CAPIQ)} companies")
print(f"Writing CompanyIntel.js to: {OUT_PATH}")

# ── JSX component ─────────────────────────────────────────────────────────────
# Written as a Python string — no f-string interpolation inside JSX blocks
# to avoid curly brace conflicts. Template literals use raw string sections.

JSX = r"""// CompanyIntel.js — Auto-generated by rebuild_company_intel.py
// Source: capiq_export.json (CapIQ exports + EDGAR rate base)
// DO NOT EDIT MANUALLY — re-run rebuild_company_intel.py to regenerate

import React, { useState, useEffect, useRef } from 'react';
import MapTab from './MapTab';

// ── Tab definitions ──────────────────────────────────────────────────────────
const TABS = [
  { id: 'overview',      label: 'Overview' },
  { id: 'financials',    label: 'Financials' },
  { id: 'rate_base',     label: 'Rate Base' },
  { id: 'customers',     label: 'Customers' },
  { id: 'capex',         label: 'CapEx Plan' },
  { id: 'dividends',     label: 'Dividends' },
  { id: 'valuation',     label: 'Valuation' },
  { id: 'guidance',      label: 'Guidance' },
  { id: 'rate_cases',    label: 'Rate Cases' },
  { id: 'transactions',  label: 'Transactions' },
  { id: 'holders',       label: 'Holders' },
  { id: 'map',           label: 'Map' },
];

// ── Utility helpers ──────────────────────────────────────────────────────────
const fmt = (v, decimals = 1) => {
  if (v === null || v === undefined || v === '' || isNaN(Number(v))) return '—';
  return Number(v).toFixed(decimals);
};

const fmtB = (v) => {
  if (!v && v !== 0) return '—';
  const n = Number(v);
  if (Math.abs(n) >= 1000) return `$${(n / 1000).toFixed(1)}T`;
  if (Math.abs(n) >= 1)    return `$${n.toFixed(1)}B`;
  return `$${(n * 1000).toFixed(0)}M`;
};

const fmtPct = (v) => (v == null ? '—' : `${Number(v).toFixed(1)}%`);

const KV = ({ label, value, highlight }) => (
  <div style={{
    display: 'flex', justifyContent: 'space-between', alignItems: 'baseline',
    padding: '6px 0', borderBottom: '1px solid #1e293b',
  }}>
    <span style={{ color: '#94a3b8', fontSize: 13 }}>{label}</span>
    <span style={{
      color: highlight ? '#38bdf8' : '#f1f5f9',
      fontWeight: highlight ? 600 : 400,
      fontSize: 14,
    }}>{value}</span>
  </div>
);

const SectionHeader = ({ children }) => (
  <div style={{
    color: '#64748b', fontSize: 11, fontWeight: 700, letterSpacing: '0.1em',
    textTransform: 'uppercase', margin: '18px 0 8px',
  }}>
    {children}
  </div>
);

const Badge = ({ text, color = '#334155' }) => (
  <span style={{
    background: color, color: '#e2e8f0', borderRadius: 4,
    padding: '2px 7px', fontSize: 12, marginRight: 4,
  }}>
    {text}
  </span>
);

const Table = ({ headers, rows, emptyMsg = 'No data available' }) => (
  <div style={{ overflowX: 'auto' }}>
    {rows.length === 0
      ? <p style={{ color: '#64748b', fontSize: 13 }}>{emptyMsg}</p>
      : (
        <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: 13 }}>
          <thead>
            <tr>
              {headers.map(h => (
                <th key={h} style={{
                  textAlign: 'left', padding: '6px 8px', color: '#64748b',
                  borderBottom: '1px solid #1e293b', fontWeight: 600,
                  whiteSpace: 'nowrap',
                }}>{h}</th>
              ))}
            </tr>
          </thead>
          <tbody>
            {rows.map((row, i) => (
              <tr key={i} style={{ background: i % 2 === 0 ? 'transparent' : '#0f172a' }}>
                {row.map((cell, j) => (
                  <td key={j} style={{
                    padding: '5px 8px', color: '#e2e8f0',
                    borderBottom: '1px solid #1e293b40',
                  }}>{cell}</td>
                ))}
              </tr>
            ))}
          </tbody>
        </table>
      )
    }
  </div>
);

// ── Tab renderers ─────────────────────────────────────────────────────────────

const OverviewTab = ({ d }) => (
  <div>
    {d.description && (
      <p style={{ color: '#cbd5e1', fontSize: 14, lineHeight: 1.6, marginBottom: 18 }}>
        {d.description}
      </p>
    )}
    <SectionHeader>Credit & Rating</SectionHeader>
    <KV label="S&P Rating" value={d.ratings?.sp || '—'} />
    <KV label="Moody's Rating" value={d.ratings?.moodys || '—'} />
    <KV label="Analysts (coverage)" value={d.analysts != null ? `${d.analysts} analysts` : '—'} />
    {d.executives && d.executives.length > 0 && (
      <>
        <SectionHeader>Management</SectionHeader>
        <Table
          headers={['Name', 'Title', 'Since']}
          rows={d.executives.map(e => [e.name, e.title, e.since || '—'])}
        />
      </>
    )}
    {d.compensation && d.compensation.length > 0 && (
      <>
        <SectionHeader>Compensation (NEO)</SectionHeader>
        <Table
          headers={['Executive', 'Total ($M)', 'Base ($M)']}
          rows={d.compensation.map(c => [
            c.name, fmt(c.total_comp_m, 2), fmt(c.base_salary_m, 2)
          ])}
        />
      </>
    )}
  </div>
);

const FinancialsTab = ({ d }) => (
  <div>
    <SectionHeader>Income Statement</SectionHeader>
    <KV label="Revenue" value={fmtB(d.revenue)} />
    <KV label="EBITDA" value={fmtB(d.ebitda)} />
    <KV label="Net Income" value={fmtB(d.net_income)} />
    <KV label="EPS" value={d.eps != null ? `$${fmt(d.eps, 2)}` : '—'} />
    <SectionHeader>Cash Flow</SectionHeader>
    <KV label="CFO" value={fmtB(d.cfo)} />
    <KV label="CapEx" value={fmtB(d.capex)} />
    <KV label="Dividends Paid" value={fmtB(d.dividends)} />
    <SectionHeader>Balance Sheet</SectionHeader>
    <KV label="Total Assets" value={fmtB(d.total_assets)} />
    <KV label="Net Debt" value={fmtB(d.net_debt)} />
    <KV label="ROE" value={fmtPct(d.roe)} />
    {d.segments && d.segments.length > 0 && (
      <>
        <SectionHeader>Segments</SectionHeader>
        <Table
          headers={['Segment', 'Revenue', 'EBITDA']}
          rows={d.segments.map(s => [
            s.name, fmtB(s.revenue), fmtB(s.ebitda)
          ])}
        />
      </>
    )}
  </div>
);

const RateBaseTab = ({ d }) => {
  const mgmt   = d.rate_base_mgmt;
  const cases  = d.rate_base_opcos || [];
  const bs     = d.net_utility_plant_latest;

  return (
    <div>
      {/* Tier 1: Management-disclosed (EDGAR investor presentations) */}
      <SectionHeader>
        Tier 1 — Management Disclosed
        <span style={{ marginLeft: 8, color: '#22c55e', fontSize: 10 }}>
          {mgmt ? '\u2713 EDGAR 8-K' : 'not found'}
        </span>
      </SectionHeader>
      {mgmt ? (
        <>
          <KV label="Total Rate Base" value={fmtB(mgmt.total_b)} highlight />
          <KV label="Year" value={mgmt.year || '—'} />
          <KV label="Source" value={mgmt.source || 'EDGAR 8-K'} />
          {mgmt.opco_breakdown && mgmt.opco_breakdown.length > 0 && (
            <Table
              headers={['OpCo', 'Rate Base', 'Year']}
              rows={mgmt.opco_breakdown.map(o => [o.opco, fmtB(o.value_b), o.year || '—'])}
            />
          )}
        </>
      ) : (
        <p style={{ color: '#64748b', fontSize: 13 }}>
          Run fetch_edgar_rate_base.py to populate management-disclosed figures.
        </p>
      )}

      {/* Tier 2: Rate case filings */}
      <SectionHeader>
        Tier 2 — Rate Case Filings
        <span style={{ marginLeft: 8, color: '#94a3b8', fontSize: 10 }}>
          {cases.length > 0 ? `${cases.length} opco(s)` : 'none'}
        </span>
      </SectionHeader>
      {cases.length > 0 ? (
        <Table
          headers={['OpCo / Label', 'Rate Base', 'Test Year', 'Status']}
          rows={cases.map(c => [
            c.label || c.opco || '—',
            c.rate_base ? fmtB(c.rate_base / 1e9) : '—',
            c.test_year || '—',
            c.status || '—',
          ])}
        />
      ) : (
        <p style={{ color: '#64748b', fontSize: 13 }}>No rate case data extracted.</p>
      )}

      {/* Tier 3: Balance sheet fallback */}
      <SectionHeader>
        Tier 3 — Balance Sheet (GAAP Fallback)
      </SectionHeader>
      <KV label="Net Utility Plant (latest)" value={bs ? fmtB(bs / 1e9) : '—'} />
      {d.net_utility_plant && d.net_utility_plant.length > 0 && (
        <Table
          headers={['Year', 'Net Utility Plant']}
          rows={d.net_utility_plant.slice(-5).map(p => [
            p.year, fmtB(p.value / 1e9)
          ])}
        />
      )}
    </div>
  );
};

const CustomersTab = ({ d }) => (
  <div>
    <KV label="Total Customers" value={
      d.total_customers_latest
        ? Number(d.total_customers_latest).toLocaleString()
        : '—'
    } highlight />
    {d.segments && d.segments.some(s => s.customers) && (
      <>
        <SectionHeader>By Segment</SectionHeader>
        <Table
          headers={['Segment', 'Customers']}
          rows={d.segments
            .filter(s => s.customers)
            .map(s => [s.name, Number(s.customers).toLocaleString()])}
        />
      </>
    )}
  </div>
);

const CapexTab = ({ d }) => (
  <div>
    <KV label="Current CapEx (annual)" value={fmtB(d.capex)} />
    {d.planned_capex && Object.keys(d.planned_capex).length > 0 && (
      <>
        <SectionHeader>Multi-Year Plan</SectionHeader>
        <Table
          headers={['Period / Label', 'Amount']}
          rows={Object.entries(d.planned_capex).map(([k, v]) => [k, fmtB(v)])}
        />
      </>
    )}
    {d.guidance && d.guidance.capex && (
      <>
        <SectionHeader>Guidance</SectionHeader>
        {typeof d.guidance.capex === 'object'
          ? Object.entries(d.guidance.capex).map(([k, v]) => (
              <KV key={k} label={k} value={fmtB(v)} />
            ))
          : <KV label="CapEx Guidance" value={fmtB(d.guidance.capex)} />
        }
      </>
    )}
  </div>
);

const DividendsTab = ({ d }) => (
  <div>
    <KV label="Annual DPS" value={d.div_per_share != null ? `$${fmt(d.div_per_share, 2)}` : '—'} />
    <KV label="Dividend Yield" value={fmtPct(d.div_yield)} />
    <KV label="Payout Ratio" value={fmtPct(d.div_payout)} />
    <KV label="Total Dividends Paid" value={fmtB(d.dividends)} />
  </div>
);

const ValuationTab = ({ d }) => (
  <div>
    <SectionHeader>Market Data</SectionHeader>
    <KV label="Price" value={d.price != null ? `$${fmt(d.price, 2)}` : '—'} />
    <KV label="Market Cap" value={fmtB(d.market_cap)} />
    <KV label="Total Enterprise Value" value={fmtB(d.tev)} />
    <SectionHeader>Multiples</SectionHeader>
    <KV label="P/E" value={d.pe != null ? `${fmt(d.pe, 1)}x` : '—'} />
    <KV label="EV/EBITDA" value={d.ev_ebitda != null ? `${fmt(d.ev_ebitda, 1)}x` : '—'} />
    <KV label="EV/EBIT" value={d.ev_ebit != null ? `${fmt(d.ev_ebit, 1)}x` : '—'} />
  </div>
);

const GuidanceTab = ({ d }) => {
  const g = d.guidance;
  if (!g || Object.keys(g).length === 0) {
    return <p style={{ color: '#64748b', fontSize: 13 }}>No guidance data extracted.</p>;
  }
  const rows = Object.entries(g)
    .filter(([k]) => k !== '_source')
    .map(([k, v]) => [k, typeof v === 'object' ? JSON.stringify(v) : String(v)]);
  return (
    <div>
      <Table headers={['Metric', 'Value / Range']} rows={rows} />
      {g._source && (
        <p style={{ color: '#64748b', fontSize: 12, marginTop: 12 }}>
          Source: {g._source}
        </p>
      )}
      {d.eps_surprise != null && (
        <>
          <SectionHeader>EPS Surprise (last quarter)</SectionHeader>
          <KV label="EPS Surprise" value={`${d.eps_surprise > 0 ? '+' : ''}${fmt(d.eps_surprise, 2)}%`}
            highlight={d.eps_surprise > 0} />
        </>
      )}
    </div>
  );
};

const RateCasesTab = ({ d }) => {
  const pending = d.pending_rate_cases || [];
  const past    = d.past_rate_cases || [];
  return (
    <div>
      <SectionHeader>Pending Rate Cases ({pending.length})</SectionHeader>
      {pending.length > 0 ? (
        <Table
          headers={['Utility / State', 'Ask ($M)', 'Test Year', 'Filed']}
          rows={pending.map(c => [
            `${c.utility || ''} ${c.state ? '(' + c.state + ')' : ''}`.trim(),
            c.ask_m != null ? `$${fmt(c.ask_m, 0)}M` : '—',
            c.test_year || '—',
            c.filed_date || '—',
          ])}
        />
      ) : (
        <p style={{ color: '#64748b', fontSize: 13 }}>No pending cases.</p>
      )}
      <SectionHeader>Concluded Rate Cases ({past.length})</SectionHeader>
      {past.length > 0 ? (
        <Table
          headers={['Utility / State', 'Ask ($M)', 'Award ($M)', 'ROE', 'Decision']}
          rows={past.map(c => [
            `${c.utility || ''} ${c.state ? '(' + c.state + ')' : ''}`.trim(),
            c.ask_m != null ? `$${fmt(c.ask_m, 0)}M` : '—',
            c.award_m != null ? `$${fmt(c.award_m, 0)}M` : '—',
            c.roe != null ? fmtPct(c.roe) : '—',
            c.decision_date || '—',
          ])}
        />
      ) : (
        <p style={{ color: '#64748b', fontSize: 13 }}>No concluded cases.</p>
      )}
    </div>
  );
};

const TransactionsTab = ({ d }) => {
  const txns = d.transactions || [];
  return (
    <div>
      <SectionHeader>M&A / Asset Transactions ({txns.length})</SectionHeader>
      {txns.length > 0 ? (
        <Table
          headers={['Date', 'Type', 'Description', 'Value']}
          rows={txns.map(t => [
            t.date || '—',
            t.type || '—',
            t.description || '—',
            t.value ? fmtB(t.value) : '—',
          ])}
        />
      ) : (
        <p style={{ color: '#64748b', fontSize: 13 }}>No transactions extracted.</p>
      )}
    </div>
  );
};

const HoldersTab = ({ d }) => {
  const holders = d.top_holders || [];
  return (
    <div>
      <SectionHeader>Top Institutional Holders</SectionHeader>
      {holders.length > 0 ? (
        <Table
          headers={['Holder', 'Shares (M)', '% O/S', 'Change']}
          rows={holders.slice(0, 15).map(h => [
            h.holder || h.name || '—',
            h.shares_m != null ? fmt(h.shares_m, 2) : '—',
            h.pct_os != null ? fmtPct(h.pct_os) : '—',
            h.change != null
              ? <span style={{ color: h.change > 0 ? '#22c55e' : '#ef4444' }}>
                  {h.change > 0 ? '+' : ''}{fmt(h.change, 2)}%
                </span>
              : '—',
          ])}
        />
      ) : (
        <p style={{ color: '#64748b', fontSize: 13 }}>No holder data extracted.</p>
      )}
    </div>
  );
};

// ── Main CompanyIntel component ───────────────────────────────────────────────

export default function CompanyIntel({ activeCompany, onMapLinkClick }) {
  const [activeTab, setActiveTab] = useState('overview');
  const [companyData, setCompanyData] = useState(null);

  // Load capiq data for selected company from /api/capiq
  useEffect(() => {
    if (!activeCompany) {
      setCompanyData(null);
      return;
    }
    fetch('/api/capiq')
      .then(r => r.json())
      .then(data => {
        // Try matching by ticker, then by name substring
        const ticker = activeCompany.toUpperCase();
        let match = data[ticker] || data[ticker.toLowerCase()];
        if (!match) {
          const key = Object.keys(data).find(k =>
            k.toUpperCase() === ticker ||
            (data[k].ticker || '').toUpperCase() === ticker
          );
          match = key ? data[key] : null;
        }
        setCompanyData(match || null);
      })
      .catch(err => console.error('CompanyIntel: capiq fetch error', err));
  }, [activeCompany]);

  // Reset to overview when company changes
  useEffect(() => {
    setActiveTab('overview');
  }, [activeCompany]);

  if (!activeCompany) {
    return (
      <div style={{
        display: 'flex', alignItems: 'center', justifyContent: 'center',
        height: '100%', color: '#475569', fontSize: 15,
      }}>
        Select a company from the Energy Map to view intelligence.
      </div>
    );
  }

  const d = companyData || {};
  const displayName = d.name || activeCompany;

  const renderTab = () => {
    switch (activeTab) {
      case 'overview':      return <OverviewTab d={d} />;
      case 'financials':    return <FinancialsTab d={d} />;
      case 'rate_base':     return <RateBaseTab d={d} />;
      case 'customers':     return <CustomersTab d={d} />;
      case 'capex':         return <CapexTab d={d} />;
      case 'dividends':     return <DividendsTab d={d} />;
      case 'valuation':     return <ValuationTab d={d} />;
      case 'guidance':      return <GuidanceTab d={d} />;
      case 'rate_cases':    return <RateCasesTab d={d} />;
      case 'transactions':  return <TransactionsTab d={d} />;
      case 'holders':       return <HoldersTab d={d} />;
      case 'map':           return (
        <MapTab
          activeCompany={activeCompany}
          onIntelClick={onMapLinkClick}
          embedded
        />
      );
      default:              return null;
    }
  };

  return (
    <div style={{
      display: 'flex', flexDirection: 'column', height: '100%',
      background: '#0f172a', color: '#e2e8f0', fontFamily: 'Inter, sans-serif',
    }}>
      {/* Header */}
      <div style={{
        padding: '16px 20px 0', borderBottom: '1px solid #1e293b',
        flexShrink: 0,
      }}>
        <div style={{ display: 'flex', alignItems: 'baseline', gap: 12, marginBottom: 12 }}>
          <h2 style={{ margin: 0, fontSize: 20, fontWeight: 700, color: '#f1f5f9' }}>
            {displayName}
          </h2>
          <span style={{ color: '#64748b', fontSize: 13 }}>{activeCompany}</span>
          {d.ratings?.sp && (
            <Badge
              text={`S&P ${d.ratings.sp}`}
              color={d.ratings.sp.startsWith('A') ? '#14532d' : '#1e3a5f'}
            />
          )}
          {onMapLinkClick && (
            <button
              onClick={() => onMapLinkClick(activeCompany)}
              style={{
                marginLeft: 'auto', background: '#1e293b', border: '1px solid #334155',
                color: '#94a3b8', borderRadius: 6, padding: '3px 10px',
                fontSize: 12, cursor: 'pointer',
              }}
            >
              \u2197 Map
            </button>
          )}
        </div>

        {/* Tab bar */}
        <div style={{ display: 'flex', gap: 0, overflowX: 'auto', paddingBottom: 0 }}>
          {TABS.map(tab => (
            <button
              key={tab.id}
              onClick={() => setActiveTab(tab.id)}
              style={{
                background: 'none',
                border: 'none',
                borderBottom: activeTab === tab.id
                  ? '2px solid #38bdf8' : '2px solid transparent',
                color: activeTab === tab.id ? '#38bdf8' : '#64748b',
                padding: '6px 12px',
                fontSize: 13,
                fontWeight: activeTab === tab.id ? 600 : 400,
                cursor: 'pointer',
                whiteSpace: 'nowrap',
                transition: 'color 0.15s',
              }}
            >
              {tab.label}
            </button>
          ))}
        </div>
      </div>

      {/* Tab content */}
      <div style={{ flex: 1, overflowY: 'auto', padding: '16px 20px' }}>
        {!companyData
          ? <p style={{ color: '#64748b', fontSize: 13 }}>
              No CapIQ data found for {activeCompany}.
              Check capiq_export.json key names match the ticker.
            </p>
          : renderTab()
        }
      </div>
    </div>
  );
}
""";

# ── Write file ─────────────────────────────────────────────────────────────────
print(f"\nWriting {len(JSX):,} chars to:\n  {OUT_PATH}")

try:
    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    with open(OUT_PATH, "w", encoding="utf-8") as f:
        f.write(JSX)
    print("\n\u2713 CompanyIntel.js written successfully.")
except FileNotFoundError:
    print(f"\nERROR: Path not found — {OUT_PATH}")
    print("If running on a different machine, update APP_SRC at top of script.")
    # Fallback: write to scripts output directory
    fallback = SCRIPT_DIR / "CompanyIntel.js"
    with open(fallback, "w", encoding="utf-8") as f:
        f.write(JSX)
    print(f"Wrote to fallback: {fallback}")
    print("Copy this file to: src/components/CompanyIntel.js")

# ── Verify: grep for key patterns ─────────────────────────────────────────────
try:
    with open(OUT_PATH if OUT_PATH.exists() else SCRIPT_DIR / "CompanyIntel.js",
              "r", encoding="utf-8") as f:
        content = f.read()

    checks = {
        "export default CompanyIntel":  "export default CompanyIntel" in content,
        "import MapTab":                "import MapTab" in content,
        "rate_base_mgmt":               "rate_base_mgmt" in content,
        "pending_rate_cases":           "pending_rate_cases" in content,
        "/api/capiq":                   "/api/capiq" in content,
        "12 tabs defined":              content.count("{ id:") >= 12,
    }

    print("\nVerification:")
    for check, ok in checks.items():
        print(f"  {'[OK]' if ok else '[FAIL]'} {check}")

    all_ok = all(checks.values())
    if all_ok:
        print("\n\u2713 All checks passed.")
    else:
        print("\n\u26a0 Some checks failed. Review CompanyIntel.js.")

except Exception as e:
    print(f"Verification error: {e}")

print("\nNext steps:")
print("  1. Run: python fetch_edgar_rate_base.py")
print("     (adds rate_base_mgmt to capiq_export.json via EDGAR)")
print("  2. Restart Node server (npm start in app directory)")
print("  3. CompanyIntel now loads from /api/capiq — no FMP calls")