#!/usr/bin/env python3
r"""tracker_progress.py — compute the %-complete tables inside POWER_ACADEMY_TRACKER.md.

Parses every checkbox item in the tracker, scores it (✅ = 100 · 🟡 = 50 · ❌/🔴 = 0),
and rewrites the block between <!-- PROGRESS:BEGIN --> and <!-- PROGRESS:END --> with
per-subsection percentages for the roadmap (sections I–VI) plus a one-line roll-up of
the ops backlogs. Run it after any status flip so the numbers are COMPUTED from the
checkboxes rather than edited by hand — the tracker's own standing rule.

Usage (PowerShell — one line):
  python E:\PowerAcademy\scripts\tracker_progress.py --tracker E:\PowerAcademy\POWER_ACADEMY_TRACKER.md --write

Without --write it prints the table and changes nothing.

Scoring notes, stated because the basis matters:
  * every checkbox item counts equally within its subsection; section and overall
    rolls are ITEM-weighted, not subsection-weighted;
  * struck-through items (~~…~~) and prose lines are not items and are not counted;
  * the roadmap universe is everything between '## I. COMPANY DEEP DIVE' and
    '## Priority'; all other checkboxes in the file roll into one 'Ops' line.
"""
import argparse, io, re, sys

BEGIN, END = "<!-- PROGRESS:BEGIN -->", "<!-- PROGRESS:END -->"
ITEM = re.compile(r"^\s*>?\s*- \[[ x]\] (✅|🟡|❌|🔴)")
SCORE = {"✅": 1.0, "🟡": 0.5, "❌": 0.0, "🔴": 0.0}
H2 = re.compile(r"^## +(.+)$")
H3 = re.compile(r"^### +(.+)$")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--tracker", required=True)
    ap.add_argument("--write", action="store_true")
    args = ap.parse_args()

    text = io.open(args.tracker, encoding="utf-8").read()
    lines = text.split("\n")

    # locate roadmap span
    try:
        start = next(i for i, l in enumerate(lines) if l.startswith("## I. COMPANY DEEP DIVE"))
        stop = next(i for i, l in enumerate(lines) if l.startswith("## Priority"))
    except StopIteration:
        sys.exit("could not find the roadmap span (## I. COMPANY DEEP DIVE … ## Priority)")

    groups = {}          # (section, subsection) -> [scores]
    order = []
    ops = []
    h2 = h3 = None
    for i, l in enumerate(lines):
        m2 = H2.match(l)
        if m2:
            h2, h3 = m2.group(1).strip(), None
        m3 = H3.match(l)
        if m3:
            h3 = m3.group(1).strip()
        m = ITEM.match(l)
        if not m:
            continue
        s = SCORE[m.group(1)]
        if start < i < stop:
            # short labels: '## I. COMPANY DEEP DIVE' + '### A. Core Company Understanding'
            sec = re.sub(r"\s*[❌🟡✅⚠️].*$", "", h2 or "?").strip()
            sub = re.sub(r"\s+\*\(.*\)\*\s*$", "", (h3 or "—")).strip()
            sub = re.sub(r"\s*[❌🟡✅].*$", "", sub).strip()
            key = (sec, sub)
            if key not in groups:
                groups[key] = []
                order.append(key)
            groups[key].append(s)
        else:
            ops.append(s)

    out = [BEGIN, "",
           "## % Complete — computed, not hand-edited",
           "",
           f"*Generated by `scripts\\tracker_progress.py` — ✅=100 · 🟡=50 · ❌=0, every item equal within its*",
           "*subsection; rolls are item-weighted. Re-run after any status flip. Edit statuses, never these numbers.*",
           "",
           "| Section | Subsection | Items | % complete |",
           "|---|---|---:|---:|"]
    all_scores = []
    cur_sec, sec_scores = None, []
    def flush_sec():
        if cur_sec and sec_scores:
            p = sum(sec_scores) / len(sec_scores)
            out.append(f"| **{cur_sec}** | **— section roll-up** | **{len(sec_scores)}** | **{p*100:.0f}%** |")
    for key in order:
        sec, sub = key
        if sec != cur_sec:
            flush_sec()
            cur_sec, sec_scores = sec, []
        ss = groups[key]
        sec_scores.extend(ss)
        all_scores.extend(ss)
        p = sum(ss) / len(ss)
        label = sub if sub != "—" else "(section-level items)"
        out.append(f"| {sec} | {label} | {len(ss)} | {p*100:.0f}% |")
    flush_sec()
    overall = sum(all_scores) / len(all_scores) if all_scores else 0
    out.append(f"| **ROADMAP I–VI** | **overall** | **{len(all_scores)}** | **{overall*100:.0f}%** |")
    if ops:
        po = sum(ops) / len(ops)
        out.append(f"| Ops backlogs & fix lists | everything outside the roadmap | {len(ops)} | {po*100:.0f}% |")
    out += ["", END]
    block = "\n".join(out)

    print(block)

    if args.write:
        if BEGIN in text and END in text:
            new = re.sub(re.escape(BEGIN) + r".*?" + re.escape(END), block, text, flags=re.S)
        else:
            # first insertion: before the Snapshot section
            anchor = "\n## Snapshot"
            if anchor not in text:
                sys.exit("no PROGRESS markers and no '## Snapshot' anchor — nowhere to insert")
            new = text.replace(anchor, "\n" + block + "\n\n---\n\n## Snapshot", 1)
        io.open(args.tracker, "w", encoding="utf-8", newline="").write(new)
        print(f"\nwritten into {args.tracker}")


if __name__ == "__main__":
    main()
